export const Colors = {
  //map
  BACKGROUND: "#1f273c",
  WALL: "#8cb2c6",
  WALL_DARK: "#495c67",
  DOOR: "#ddc275",

  //pickups
  HEALTHPOTION: "#FF00FF",
  NUTELLABUN: "#ddc275",
  SCROLL_OF_LIGHTING: "#00FFFF",
  SCROLL_OF_FIREBALL: "#FFAA00",
  SCROLL_OF_CONFUSION: "#FFFFAA",
  SCROLL_OF_MAP: "#AAAA22",

  //ui
  LEVEL_UP: "#FFFF00",
  HEALED: "#8F8",
  MENU_CURSOR: "#AAA",
  GAME_SAVED: "#0FA",
  PICKED_UP: "#AAA",
  INVENTORY_FULL: "#F00",
  MENU_BORDER: "#AAA",

  ALLOWED: "#FFF",
  DISALLOWED: "#F88",

  HP_10_PERCENT: "#F44",
  HP_25_PERCENT: "#F88",
  HP_50_PERCENT: "#FAA",
  HP_95_PERENT: "#AAA",
  HP_MAX: "#AFA",

  //actors
  HERO: "#FFF",
  STAIRS: "#FFF",

  //log
  PLAYER_ATTACK: "#DDD",
  ENEMY_ATTACK: "#AAA",
  DEAD_BODY: "#A00",
  DEFAULT_TEXT: "#AAA",

  DEFEAT: "#A00",
};
